export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAILURE = "FETCH_PRODUCTS_FAILURE";
export const LOAD_MORE_PRODUCTS = "LOAD_MORE_PRODUCTS";
export const LOAD_MORE_PRODUCTS_SUCCESS = "LOAD_MORE_PRODUCTS_SUCCESS";
export const LOAD_MORE_PRODUCTS_FAILURE = "LOAD_MORE_PRODUCTS_FAILURE";
export const ALL_PRODUCTS_LOADED = "ALL_PRODUCTS_LOADED";
export const RESET_PRODUCTS = "RESET_PRODUCTS";